@api = http://localhost:3000/

#####
GET {{api}}usuarios/get-usuarios

###
GET {{api}}usuarios/get-usuario/1

###
POST {{api}}usuarios/create-usuario
Content-Type: application/json

{
    "Nombre": "Isaac",
    "Apellido":"Gonzalez",
    "Correo": "a@a.com",
    "Contrasena": "123",
    "Curp": "GOOI",
    "Telefono": "12345"
}

###
DELETE {{api}}usuarios/delete-usuario/1


##### Tabla Companias

#####
GET {{api}}companias/get-companias

###
GET {{api}}companias/get-compania/1

###
POST {{api}}companias/create-compania
Content-Type: application/json

{
    "Nombre": "Gonzer S.A C.V",
    "Ubicacion":"Ags ags",
    "Descripcion": "Empresa agendadora",
    "SitioWeb": "www.web.com",
    "Contacto": "asd@ac.com"
}